<?php

return [

    'edition' => env('CORELIX_EDITION', 'pro'),

    'upgrade_url' => env('CORELIX_UPGRADE_URL', 'https://corelix.io/pricing'),

    'registry' => [
        [
            'key' => 'GRANULAR_PERMISSIONS',
            'name' => 'Granular Permissions',
            'description' => 'Project-level and environment-level access control with role-based overrides',
            'tier' => 'free',
            'default' => true,
            'category' => 'permissions',
            'env_var' => 'FEATURE_GRANULAR_PERMISSIONS',
            'parent' => null,
        ],
        [
            'key' => 'ENCRYPTED_S3_BACKUPS',
            'name' => 'Encrypted S3 Backups',
            'description' => 'Per-storage NaCl SecretBox encryption for database backups',
            'tier' => 'free',
            'default' => true,
            'category' => 'backups',
            'env_var' => 'FEATURE_ENCRYPTED_S3_BACKUPS',
            'parent' => null,
        ],
        [
            'key' => 'RESOURCE_BACKUPS',
            'name' => 'Resource Backups',
            'description' => 'Volume, configuration, and full backups for any resource type',
            'tier' => 'free',
            'default' => true,
            'category' => 'backups',
            'env_var' => 'FEATURE_RESOURCE_BACKUPS',
            'parent' => null,
        ],
        [
            'key' => 'CUSTOM_TEMPLATE_SOURCES',
            'name' => 'Custom Template Sources',
            'description' => 'External GitHub repositories as sources for docker-compose service templates',
            'tier' => 'free',
            'default' => true,
            'category' => 'deployment',
            'env_var' => 'FEATURE_CUSTOM_TEMPLATE_SOURCES',
            'parent' => null,
        ],
        [
            'key' => 'ENHANCED_DATABASE_CLASSIFICATION',
            'name' => 'Enhanced Database Classification',
            'description' => 'Expanded database image detection list with explicit classification labels',
            'tier' => 'free',
            'default' => true,
            'category' => 'deployment',
            'env_var' => 'FEATURE_ENHANCED_DATABASE_CLASSIFICATION',
            'parent' => null,
        ],
        [
            'key' => 'NETWORK_MANAGEMENT',
            'name' => 'Network Management',
            'description' => 'Per-environment Docker network isolation and shared networks',
            'tier' => 'free',
            'default' => true,
            'category' => 'networking',
            'env_var' => 'FEATURE_NETWORK_MANAGEMENT',
            'parent' => null,
        ],
        [
            'key' => 'PROXY_ISOLATION',
            'name' => 'Proxy Isolation',
            'description' => 'Dedicated proxy network for FQDN-only traffic routing',
            'tier' => 'free',
            'default' => true,
            'category' => 'networking',
            'env_var' => 'FEATURE_PROXY_ISOLATION',
            'parent' => 'NETWORK_MANAGEMENT',
        ],
        [
            'key' => 'SWARM_OVERLAY_ENCRYPTION',
            'name' => 'Swarm Overlay Encryption',
            'description' => 'IPsec encryption for Docker Swarm overlay networks',
            'tier' => 'free',
            'default' => true,
            'category' => 'networking',
            'env_var' => 'FEATURE_SWARM_OVERLAY_ENCRYPTION',
            'parent' => 'NETWORK_MANAGEMENT',
        ],
        [
            'key' => 'MCP_ENHANCED_TOOLS',
            'name' => 'MCP Enhanced Tools',
            'description' => 'Enhanced MCP tools for AI-driven infrastructure management',
            'tier' => 'free',
            'default' => true,
            'category' => 'deployment',
            'env_var' => 'FEATURE_MCP_ENHANCED_TOOLS',
            'parent' => null,
        ],
        [
            'key' => 'ENHANCED_UI_THEME',
            'name' => 'Enhanced UI Themes',
            'description' => 'Multi-theme selector with corporate-grade visual themes',
            'tier' => 'free',
            'default' => true,
            'category' => 'ui',
            'env_var' => 'FEATURE_ENHANCED_UI_THEME',
            'parent' => null,
        ],
        [
            'key' => 'ADDITIONAL_BUILD_TYPES',
            'name' => 'Additional Build Types',
            'description' => 'Railpack, Heroku Buildpacks, and Paketo Buildpacks build options',
            'tier' => 'free',
            'default' => true,
            'category' => 'deployment',
            'env_var' => 'FEATURE_ADDITIONAL_BUILD_TYPES',
            'parent' => null,
        ],
        [
            'key' => 'CLUSTER_MANAGEMENT',
            'name' => 'Cluster Management',
            'description' => 'Docker Swarm cluster dashboard, node management, and visualization',
            'tier' => 'pro',
            'default' => true,
            'category' => 'monitoring',
            'env_var' => 'FEATURE_CLUSTER_MANAGEMENT',
            'parent' => null,
        ],
        [
            'key' => 'WHITELABELING',
            'name' => 'Whitelabeling',
            'description' => 'Build-time brand identity replacement with runtime URL overrides',
            'tier' => 'pro',
            'default' => true,
            'category' => 'branding',
            'env_var' => 'FEATURE_WHITELABELING',
            'parent' => null,
        ],
        [
            'key' => 'DOCKER_REGISTRY_MANAGEMENT',
            'name' => 'Docker Registry Management',
            'description' => 'Multiple Docker registry management with authentication',
            'tier' => 'pro',
            'default' => true,
            'category' => 'deployment',
            'env_var' => 'FEATURE_DOCKER_REGISTRY_MANAGEMENT',
            'parent' => null,
        ],
        [
            'key' => 'AUDIT_TRAIL',
            'name' => 'Audit Trail',
            'description' => 'Comprehensive audit trail with export and retention policies',
            'tier' => 'pro',
            'default' => false,  // Not yet implemented — keep disabled until v2
            'category' => 'compliance',
            'env_var' => 'FEATURE_AUDIT_TRAIL',
            'parent' => null,
        ],
    ],

];
